services:
  - type: web
    name: simple-weather
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - src: /.*
        dest: /index.html
    autoDeploy: true
